### ISSUE TITLE
 What is the difference between this and AssemblyScript？

### ISSUE THREAD

**Issue by beautiful-boyyy** [intel/Wasmnizer-ts#112]
I just started learning webassembly, and I feel that [AssemblyScript](https://www.assemblyscript.org/) and this project seem to be doing the same things. What's the difference?

**Comment by xujuntwt95329** [comment]
Hi, `AssemblyScript` compiles a TypeScript-like language to WebAssembly, it doesn't allow dynamic language features such as `any`, `union` and so on, the objects are inside `wasm linear memory`, managed through a garbage collector built into WebAssembly

`Wasmnizer-ts` compiles a subset of TypeScript to WebAssembly, leveraging [WasmGC proposal](https://github.com/WebAssembly/gc/tree/main), the objects are in WasmGC heap, managed by the underlining wasm runtimes, and a series of APIs (libdyntype API) are introduced to work as an escape hatch for dynamic objects.

**Comment by beautiful-boyyy** [comment]
> Hi, `AssemblyScript` compiles a TypeScript-like language to WebAssembly, it doesn't allow dynamic language features such as `any`, `union` and so on, the objects are inside `wasm linear memory`, managed through a garbage collector built into WebAssembly
> 
> `Wasmnizer-ts` compiles a subset of TypeScript to WebAssembly, leveraging [WasmGC proposal](https://github.com/WebAssembly/gc/tree/main), the objects are in WasmGC heap, managed by the underlining wasm runtimes, and a series of APIs (libdyntype API) are introduced to work as an escape hatch for dynamic objects.

I get it, thanks.
