### ISSUE TITLE
Cannot build ts source code

### ISSUE THREAD

**Issue by beautiful-boyyy** [intel/Wasmnizer-ts#122]
I followed steps in get_started.md,  but I got this error.
![Screenshot 2023-12-21 at 17 06 47](https://github.com/intel/Wasmnizer-ts/assets/66351806/839fe952-5fe4-4d64-8c08-28096714c42b)

sys: macos 14
node: 18.12.1

**Comment by xujuntwt95329** [comment]
Hi, this is strange, could you please check the file `build/lib/builtin/builtin_name.js` to see if there is `export var BuiltinNames;`?

We mostly test it on ubuntu, I'll add a CI for MacOS to see if we can reproduce this issue

**Comment by beautiful-boyyy** [comment]
> Hi, this is strange, could you please check the file `build/lib/builtin/builtin_name.js` to see if there is `export var BuiltinNames;`?
> 
> We mostly test it on ubuntu, I'll add a CI for MacOS to see if we can reproduce this issue

![Screenshot 2023-12-21 at 17 39 30](https://github.com/intel/Wasmnizer-ts/assets/66351806/549752e7-1712-487a-8e91-844f5c42edb8)

**Comment by xujuntwt95329** [comment]
Seems the generated file is different with that on my machine, I add a CI to test compilation on MacOS and seems it works well:
https://github.com/intel/Wasmnizer-ts/actions/runs/7287061049/job/19856944342?pr=123
(the MacOS 14 runner seems not available, this action is executed under MacOS 12)

Could you use the Github codespace to have a try? I may need to find a MacOS machine to test this issue

**Comment by beautiful-boyyy** [comment]
> Seems the generated file is different with that on my machine, I add a CI to test compilation on MacOS and seems it works well: https://github.com/intel/Wasmnizer-ts/actions/runs/7287061049/job/19856944342?pr=123 (the MacOS 14 runner seems not available, this action is executed under MacOS 12)
> 
> Could you use the Github codespace to have a try? I may need to find a MacOS machine to test this issue

My problem, I redownload the repo again, everything is ok.
